spring:
  application:
    name: DomainRegistrationLive

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/DomainRegistrationLiveDashboardDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:naman1234}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch-size: 100
        order-inserts: true

splitter:
  url: ${SPLITTER_URL:http://localhost:8000}
  connect-timeout: 2s
  read-timeout: 10s

segmentation:
  batch-size: 100
  max-attempts: 5
  idle-sleep: 2s
  error-backoff: 5s

snapshot:
  interval: 10s
  initial-delay: 3s
  snapshots-to-keep: 500
  top-keywords: 15

cors:

  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

collector:
  enabled: true
  rdap-workers: 4
  max-age: 360m
  rdap-max-per-host-per-second: 5
  certstream-url: ${COLLECTOR_CERTSTREAM_URL:ws://localhost:8081/}