spring:
  application:
    name: DomainRegistrationLive

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/DomainRegistrationLiveDashboardDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:naman1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch-size: 100
        order-inserts: true

splitter:
  url: http://localhost:8000
  connect-timeout: 2s
  read-timeout: 10s

segmentation:
  batch-size: 100
  max-attempts: 5
#  change idle time to 1 sec later
  idle-sleep: 5s
  error-backoff: 5s

snapshot:
  interval: 10s
  initial-delay: 3s
  snapshots-to-keep: 500
  top-keywords: 15